### ISSUE TITLE
TODO: v1

### ISSUE THREAD

**Issue by VictorKoenders** [bincode-org/bincode-core#2]
- [x] Implement `serialize_size`
- [x] Implement `deserialize_enum` or document why it should error
- [ ] Get rid of `.expect`
  - Serializer::serialize_seq with no length
  - Serializer::serialize_map with no length
- [x] Test with `alloc` feature
- [ ] Refactor code so the codebase is clean
- [x] Add missing docs
- [ ] Review all docs

Some panics in the code:
- [ ] Whenever serde throws a custom error (`impl serde::de::Error for DeserializeError` and `impl serde::ser::Error for SerializeError`)
- [ ] Deserializer::deserialize_any
- [ ] Deserializer::deserialize_identifier
- [ ] Deserializer::deserialize_ignored_any
- [ ] Serializer::collect_str (this accepts `T: core::fmt::Display`, we could make our own formatter and pass this to display)

**Comment by almusil** [comment]
Hello,
I would really love to use bincode on embedded. I was wondering how usable is current implementation? 
Is there anything I could help with? Preferably some low hanging fruits first to get familiar with the code. 
Thanks

**Comment by VictorKoenders** [comment]
I know the library works for the examples in tests/simple.rs. Outside if that we haven't tested anything.

I think a good place to start is to add tests and see what works and what does not. I'm thinking something along the likes of:
- Arrays of types (`[u32; 10]`, `[SomeStruct; 5]`)
- Enums with variants (`enum Val { A(u32), B(u32) }`)
- C-style enums (`enum Val { A, B }`)
- `&str` and `&[u8]`

Depending on your use-case, you can add more tests.

We'd love to get a PR for tests, failing or succeeding, so we can get a better view on how complete this library is.

**Comment by VictorKoenders** [comment]
bincode 2.0-alpha.0 is out, which should replace this crate completely
